spring:
  application:
    name: PRODUCT-SERVICE

  jmx:
    enabled: true

  datasource:
    url: jdbc:mariadb://${DBHost:localhost}:3306/productdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: Thakur@7

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
    import: configserver:http://localhost:8888

server:
  port: 8080