spring:
  application:
    name: PAYMENT-SERVICE

  jmx:
    enabled: true

  datasource:
    url: jdbc:mariadb://${DBHost:localhost}:3306/paymentdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: Thakur@7

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
    import: configserver:http://localhost:8888

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecom
          jwk-set-uri: http://localhost:8080/realms/ecom/protocol/openid-connect/certs

server:
  port: 8081